CREATE TABLE ROOM_INFO (
	ROOM_NO VARCHAR(5) NOT NULL COMMENT '¹æ¹øÈ£',
	LAST_MESURE_DT DATETIME NOT NULL COMMENT 'ÃÖÁ¾ÃøÁ¤ÀÏ½Ã',
	CO2_DNSTY DOUBLE NULL DEFAULT NULL COMMENT 'CO2³óµµ',
	INDOOR_HD DOUBLE NULL DEFAULT NULL COMMENT '½Ç³»½Àµµ',
	LIGHT_IN DOUBLE NULL DEFAULT NULL COMMENT '±¤µµ',
	PIR_SENSOR DOUBLE NULL DEFAULT NULL COMMENT 'PIR¼¾¼­',
	INDOOR_TP DOUBLE NULL DEFAULT NULL COMMENT '½Ç³»¿Âµµ',
	REGIST_DT DATETIME NULL DEFAULT NULL COMMENT 'µî·ÏÀÏ½Ã',
	UPDT_DT DATETIME NULL DEFAULT NULL COMMENT '°»½ÅÀÏ½Ã',
	PRIMARY KEY (ROOM_NO)
)
COMMENT='¹æÁ¤º¸';
