CREATE TABLE SENSOR_DATA (
	ROOM_NO VARCHAR(5) NOT NULL COMMENT '방번호',
	MESURE_DT DATETIME NOT NULL COMMENT '측정일시',
	CO2_DNSTY DOUBLE NULL DEFAULT NULL COMMENT 'CO2농도',
	INDOOR_HD DOUBLE NULL DEFAULT NULL COMMENT '실내습도',
	LIGHT_IN DOUBLE NULL DEFAULT NULL COMMENT '광도',
	PIR_SENSOR DOUBLE NULL DEFAULT NULL COMMENT 'PIR센서',
	INDOOR_TP DOUBLE NULL DEFAULT NULL COMMENT '실내온도',
	REGIST_DT DATETIME NULL DEFAULT NULL COMMENT '등록일시',
	UPDT_DT DATETIME NULL DEFAULT NULL COMMENT '갱신일시',
	PRIMARY KEY (ROOM_NO, MESURE_DT)
)
COMMENT='센서데이터';
